name: Spiders Scheduler

on:
  schedule:
    - cron: '0 18 * * 5' # Every Friday at 18:00 UTC
  workflow_dispatch:

jobs:
  scheduler:

    name: Schedule all spiders on Zyte production project
    runs-on: ubuntu-latest

    env:
      SHUB_PROJECTID: ${{ secrets.scrapycloud_project_id }}
      SHUB_APIKEY: ${{ secrets.scrapycloud_api_key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'
      - name: Install pipenv
        run: |
          pip --quiet install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Schedule spiders
        shell: bash
        run: |
          pipenv run scrapy schedule_all ${SHUB_PROJECTID}
